'use client';
import { useEffect,useRef,useState,type ReactNode } from 'react';
import { Download,LocateFixed,Upload,Check,LoaderCircle,Smartphone } from 'lucide-react';
import { Choice,ToggleRow } from './Controls';
import { Slider } from '@/components/ui/slider';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from '@/components/ui/accordion';
import { useUI } from '@/lib/siddur/i18n-context';
import { UI_LANGUAGES } from '@/lib/siddur/i18n';
import { PLACES,validateLocation,placeFromCoordinates } from '@/lib/siddur/core';
import { LANGUAGES } from '@/lib/siddur/reading';
import type { Settings,Place,PersonalTranslations } from '@/lib/siddur/types';

function SettingsCategory({value,title,description,children}:{value:string;title:string;description?:string;children:ReactNode}){
 const {t}=useUI();
 return <AccordionItem value={value} className="settings-category"><AccordionTrigger className="settings-category-trigger"><span><strong>{t(title)}</strong>{description&&<span className="settings-category-description">{t(description)}</span>}</span></AccordionTrigger><AccordionContent className="settings-card">{children}</AccordionContent></AccordionItem>;
}

export function SettingsView({settings,patch,personal,setPersonal,onInstall,installable}:{settings:Settings;patch:(v:Partial<Settings>)=>void;personal:PersonalTranslations;setPersonal:(p:PersonalTranslations)=>void;onInstall:()=>void;installable:boolean}){
 const {t}=useUI();
 const [place,setPlace]=useState<Place>(settings.place),[notice,setNotice]=useState(''),[locating,setLocating]=useState(false),[offline,setOffline]=useState(''),[progress,setProgress]=useState<number|null>(null);const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>setPlace(settings.place),[settings.place]);
 function savePlace(){const error=validateLocation(place);if(error){setNotice(error);return;}patch({place:{...place,name:place.name.trim()||'Custom location'}});setNotice('Location saved. Your calendar and prayer times have been updated.');}
 function locate(){if(!navigator.geolocation){setNotice('Location is not supported by this browser. Enter your coordinates below.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;setPlace(placeFromCoordinates(Number(p.coords.latitude.toFixed(5)),Number(p.coords.longitude.toFixed(5)),tz,p.coords.altitude));setNotice('Location found. Check the device time zone and Israel/diaspora setting, then save.');setLocating(false);},()=>{setNotice('Location access was unavailable. Choose a city or enter coordinates below.');setLocating(false);},{timeout:15000,maximumAge:0,enableHighAccuracy:true});}
 async function download(){setProgress(0);setOffline('Preparing your offline library…');try{if(!('caches' in window)||!('serviceWorker' in navigator))throw Error('Offline storage is not supported by this browser.');const registration=await navigator.serviceWorker.getRegistration();if(!registration?.active)throw Error('Offline mode is not ready yet. Reopen the installed app online, then try again.');const response=await fetch('/offline-manifest.json',{cache:'no-store'});if(!response.ok)throw Error('The offline file list is unavailable.');const data=await response.json() as {urls:string[];cacheName:string};const urls:string[]=data.urls;const cache=await caches.open(data.cacheName);let done=0;for(let i=0;i<urls.length;i+=4){await Promise.all(urls.slice(i,i+4).map(async url=>{const asset=await fetch(url);if(!asset.ok)throw Error('A text could not be downloaded. Reconnect and try again.');await cache.put(url,asset);done++;setProgress(Math.round(done/urls.length*100));}));}if(navigator.storage?.persist)await navigator.storage.persist();setOffline('All included texts and the app are saved for offline reading. Your browser may remove offline data if device storage runs low.');}catch(e){setOffline(e instanceof Error?e.message:'Download interrupted. Please try again.');}finally{setProgress(null);}}
 function exportTranslations(){const blob=new Blob([JSON.stringify({format:'kavvanah-translations-v1',translations:personal},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kavvanah-translations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importTranslations(file:File){try{if(file.size>5_000_000)throw Error('This file is too large (maximum 5 MB).');const data=JSON.parse(await file.text());if(data.format!=='kavvanah-translations-v1'||!data.translations||typeof data.translations!=='object'||Array.isArray(data.translations))throw Error('Choose a Kavvanah translation export.');const pairs=Object.entries(data.translations);if(pairs.some(([k,v])=>!/(?:en|ru|uk)$/.test(k)||typeof v!=='string'||v.length>30000))throw Error('The translation file contains invalid entries.');setPersonal({...personal,...data.translations});setNotice(t('{count} personal translations imported.',{count:pairs.length}));}catch(e){setNotice(e instanceof Error?e.message:'This file could not be imported.');}if(fileInput.current)fileInput.current.value='';}
 const languageOptions=Object.entries(LANGUAGES).map(([value,label])=>({value,label}));
 return <div className="settings-view">
 <Accordion type="multiple" defaultValue={[]} className="settings-categories"><SettingsCategory value="location" title="Your location" description="Prayer times follow this place and its time zone."><div className="field"><label>{t("Choose a city")}</label><Choice label="Choose a city" value={PLACES.find(p=>p.name===place.name)?.name??'custom'} options={[...PLACES.map(p=>({value:p.name,label:p.name})),{value:'custom',label:'Custom location'}]} onChange={v=>{const p=PLACES.find(p=>p.name===v);if(p){setPlace(p);patch({place:p});setNotice('City updated.');}}}/></div><button className="button subtle full-width" disabled={locating} onClick={locate}>{locating?<LoaderCircle className="spin" size={17}/>:<LocateFixed size={17}/>}{t("Use my current location")}</button><div className="field"><label htmlFor="location-name">{t("Location name")}</label><input id="location-name" value={t(place.name)} onChange={e=>setPlace({...place,name:e.target.value})}/></div><div className="field-pair"><div className="field"><label htmlFor="latitude">{t("Latitude")}</label><input id="latitude" type="number" min={-90} max={90} step="any" value={Number.isFinite(place.latitude)?place.latitude:''} onChange={e=>setPlace({...place,latitude:e.target.value===''?NaN:Number(e.target.value)})}/></div><div className="field"><label htmlFor="longitude">{t("Longitude")}</label><input id="longitude" type="number" min={-180} max={180} step="any" value={Number.isFinite(place.longitude)?place.longitude:''} onChange={e=>setPlace({...place,longitude:e.target.value===''?NaN:Number(e.target.value)})}/></div></div><div className="field"><label htmlFor="timezone">{t("Time zone")}</label><input id="timezone" dir="ltr" placeholder={t("Asia/Jerusalem")} value={place.timeZone} onChange={e=>setPlace({...place,timeZone:e.target.value})}/><p className="field-hint">{t("Choose the time zone of the selected location. The clock uses your device time.")}</p></div><button className="button subtle" type="button" onClick={()=>setPlace({...place,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone})}>{t("Use device time zone")}</button><div className="field-pair"><div className="field"><label htmlFor="elevation">{t("Elevation (metres)")}</label><input id="elevation" type="number" min={0} max={9000} value={Number.isFinite(place.elevation)?place.elevation:''} onChange={e=>setPlace({...place,elevation:e.target.value===''?NaN:Number(e.target.value)})}/></div><div className="field"><label>{t("Holiday calendar")}</label><Choice label="Holiday calendar" value={place.israel?'israel':'diaspora'} onChange={v=>setPlace({...place,israel:v==='israel'})} options={[{value:'israel',label:'Israel'},{value:'diaspora',label:'Diaspora'}]}/></div></div><button className="button primary full-width" onClick={savePlace}><Check size={17}/>{t("Save location")}</button></SettingsCategory>
 <SettingsCategory value="reading" title="Reading preferences" description="Text tradition and pronunciation are separate."><div className="field"><label>{t("Prayer text tradition")}</label><Choice label="Settings prayer tradition" value={settings.nusach} onChange={v=>patch({nusach:v as Settings['nusach']})} options={[{value:'ashkenaz',label:'Nusach Ashkenaz'},{value:'edot',label:'Edot HaMizrach · Sephardi'}]}/></div><div className="field"><label>{t("Pronunciation style")}</label><Choice label="Settings pronunciation" value={settings.pronunciation} onChange={v=>patch({pronunciation:v as Settings['pronunciation']})} options={[{value:'sephardi',label:'Sephardi / Israeli'},{value:'ashkenazi',label:'Ashkenazi'}]}/></div><div className="field-pair"><div className="field"><label>{t("Transliteration")}</label><Choice label="Settings transliteration language" value={settings.transliterationLanguage} options={languageOptions} onChange={v=>patch({transliterationLanguage:v as Settings['transliterationLanguage']})}/></div><div className="field"><label>{t("Translation")}</label><Choice label="Settings translation language" value={settings.translationLanguage} options={languageOptions} onChange={v=>patch({translationLanguage:v as Settings['translationLanguage']})}/></div></div></SettingsCategory>
 <SettingsCategory value="appearance" title="Appearance"><div className="field"><label>{t("App language")}</label><Choice label="App language" value={settings.uiLanguage} onChange={v=>patch({uiLanguage:v as Settings['uiLanguage']})} options={Object.entries(UI_LANGUAGES).map(([value,label])=>({value,label}))}/></div><div className="field"><label>{t("Clock format")}</label><Choice label="Clock format" value={settings.clockFormat} onChange={v=>patch({clockFormat:v as Settings['clockFormat']})} options={[{value:'24h',label:'24-hour'},{value:'12h',label:'12-hour (AM/PM)'}]}/></div><div className="field"><label>{t("Theme")}</label><Choice label="Theme" value={settings.theme} onChange={v=>patch({theme:v as Settings['theme']})} options={[{value:'light',label:'Light'},{value:'dark',label:'Dark'},{value:'black',label:'Amoled'},{value:'paper',label:'Paper'},{value:'dark-paper',label:'Dark paper'},{value:'system',label:'Match device'}]}/></div><div className="field"><label>{t("Main app color")}</label><Choice label="Main app color" value={settings.accent} onChange={v=>patch({accent:v as Settings['accent']})} options={[{value:'blue',label:'Blue'},{value:'gold',label:'Gold'},{value:'teal',label:'Teal'},{value:'plum',label:'Plum'},{value:'terracotta',label:'Terracotta'},{value:'green',label:'Green'},{value:'amber',label:'Amber'},{value:'rose',label:'Rose'},{value:'violet',label:'Violet'},{value:'slate',label:'Slate'},{value:'olive',label:'Olive'},{value:'cyan',label:'Cyan'}]}/></div><div className="field"><label>{t("Hebrew text size")} <span>{settings.textSize}{t("px")}</span></label><Slider aria-label={t("Settings text size")} min={20} max={44} step={1} value={[settings.textSize]} onValueChange={v=>patch({textSize:v[0]})}/></div><div className="field"><label>{t("Font style")}</label><Choice label="Settings font style" value={settings.font} onChange={v=>patch({font:v as Settings['font']})} options={[{value:'serif',label:'Hebrew serif'},{value:'sans',label:'Sans serif'}]}/></div><ToggleRow label="Show vowel marks" checked={settings.vowels} onChange={v=>patch({vowels:v})}/></SettingsCategory>
 <SettingsCategory value="calendar" title="Calendar"><div className="field"><label>{t("Calendar presentation")}</label><Choice label="Calendar presentation" value={settings.calendarMode} onChange={v=>patch({calendarMode:v as Settings['calendarMode']})} options={[{value:'hebrew',label:'Hebrew calendar'},{value:'gregorian',label:'Gregorian calendar'}]}/></div></SettingsCategory>
 <SettingsCategory value="times" title="Prayer-time calculations" description="Choose the methods followed by your community."><div className="field"><label>{t("Latest Shema & Shacharit")}</label><Choice label="Zmanim calculation method" value={settings.zmanMethod} onChange={v=>patch({zmanMethod:v as Settings['zmanMethod']})} options={[{value:'gra',label:'GRA · sunrise to sunset'},{value:'mga',label:'MGA · 72 minutes before / after'}]}/></div><div className="field"><label>{t("Nightfall / Havdalah")}</label><Choice label="Nightfall method" value={settings.nightfall} onChange={v=>patch({nightfall:v as Settings['nightfall']})} options={[{value:'8.5',label:'8.5° below horizon'},{value:'7.083',label:'7.083° below horizon'},{value:'72',label:'72 minutes after sunset'}]}/></div><div className="field"><label htmlFor="candles">{t("Candle lighting · minutes before sunset")}</label><input id="candles" type="number" min={0} max={90} value={settings.candleMinutes} onChange={e=>patch({candleMinutes:Number(e.target.value)})}/><p className="field-hint">{t("18 is common; Jerusalem commonly uses 40. Choose your local custom.")}</p></div><ToggleRow label="Show prayer shortcuts" description="Open the related prayer from the prayer-times list." checked={settings.prayerLinks} onChange={v=>patch({prayerLinks:v})}/><ToggleRow label="Adjust for elevation" description="Affects sunrise/sunset-based times." checked={settings.useElevation} onChange={v=>patch({useElevation:v})}/></SettingsCategory>
 <SettingsCategory value="offline" title="Take your siddur with you" description="No account needed. Your settings stay private."><button className="button primary full-width" onClick={onInstall}><Smartphone size={17}/>{t(installable?'Install Kavvanah':'How to install the app')}</button><button className="button subtle full-width" disabled={progress!==null} onClick={download}><Download size={17}/>{progress!==null?t('Downloading · {progress}%',{progress}):t('Download all texts for offline use')}</button>{progress!==null&&<progress max={100} value={progress} aria-label={t("Offline download progress")}/>}{offline&&<p className="notice" role="status">{t(offline)}</p>}<div className="settings-divider"/><h3>{t("Personal translations")}</h3><p className="field-hint">{t('{count} saved passages. Export a backup to move them to another device.',{count:Object.keys(personal).length})}</p><div className="field-pair"><button className="button subtle" onClick={exportTranslations}><Download size={16}/>{t("Export")}</button><button className="button subtle" onClick={()=>fileInput.current?.click()}><Upload size={16}/>{t("Import")}</button></div><input ref={fileInput} type="file" accept=".json,application/json" className="hidden" aria-label={t("Import translations file")} onChange={e=>{if(e.target.files?.[0])importTranslations(e.target.files[0]);}}/></SettingsCategory>
 <SettingsCategory value="sources" title="Text editions & attribution"><p className="subtle-note">{t("Kavvanah uses Sefaria text editions and Hebcal calendar calculations. English translations have edition-specific licenses shown in the reader. The full Tanakh is included; siddur content follows the available source editions, including their omissions. This version does not include a separate High Holiday machzor or Nusach Sefard edition.")}</p></SettingsCategory></Accordion>{notice&&<p className="notice settings-notice" role="status">{t(notice)}</p>}</div>;
}
